version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: otp_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: otp_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis